version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-keycloak.sql:/docker-entrypoint-initdb.d/init-keycloak.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

    ports: ["8080:8080"]
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "for i in {1..20}; do http --check-status GET http://localhost:8080/health/ready > /dev/null 2>&1 && exit 0 || sleep 5; done; exit 1",
        ]

  keycloak-fix:
    image: quay.io/keycloak/keycloak:21.1.1
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: ["/bin/bash", "-c"]
    command: |
      until http --check-status GET http://keycloak:8080/health/ready >/dev/null 2>&1; do sleep 3; done;
      /opt/keycloak/bin/kcadm.sh config credentials --server http://keycloak:8080 --realm master --user ${KEYCLOAK_ADMIN} --password ${KEYCLOAK_ADMIN_PASSWORD}
      /opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE || true

  vault:
    image: hashicorp/vault:1.17.3
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - vaultdata:/vault/data
      - ./vault.hcl:/vault/config/vault.hcl:ro
    ports:
      - "8200:8200"
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 10s
      retries: 20

volumes:
  pgdata:
  vaultdata:
