name: test-terraform-localstack

on:
  workflow_dispatch:
  push:
    branches: [willcloud-keycloak-ec2-localstack-test]

jobs:
  localstack-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: "latest"
          install-awslocal: "true"

      - name: Wait for LocalStack
        run: |
          echo "Waiting for LocalStack to be ready..."
          for i in {1..30}; do
          awslocal sts get-caller-identity && break
          sleep 2
          done

      - name: Generate SSH key for Terraform
        run: |
          ssh-keygen -t rsa -b 4096 -f ./id_rsa_localstack -N ""
          ls -al .

      - name: Install Terraform manually
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip -o tf.zip
          unzip tf.zip
          sudo mv terraform /usr/local/bin/
          terraform version

      - name: Fix Terraform binary for tflocal
        run: |
          echo "TERRAFORM_CLI_PATH=/usr/local/bin/terraform" >> $GITHUB_ENV

      - name: Install tflocal
        run: |
          pip install terraform-local awscli-local

      - name: Run Terraform
        working-directory: .
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          tflocal init -no-color
          tflocal plan -no-color
          tflocal apply -auto-approve -no-color
