name: Terraform LocalStack Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --env SERVICES=s3,lambda,dynamodb
          --env DEBUG=1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Init Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
