name: Deploy to LocalStack

on:
  push:
    branches: [willcloud-s3-localstack-test]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 10s
          --health-retries 10
          --health-timeout 5s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform (simulate AWS infra)
        run: terraform apply -auto-approve
