name: Terraform Deploy with LocalStack

on:
  push:
    branches: ["willcloud-ec2-localstack-test"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: "ec2,iam,s3,sts,cloudwatch,logs"
          DEBUG: 1
        options: >-
          --health-cmd="curl -f http://localhost:4566/health || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
